### ISSUE TITLE
Bug: spearman moved out of his body

### ISSUE THREAD

**Issue by StyMaar** [ozkriff/zemeroth#287]
![capture du 2018-06-25 12-57-56](https://user-images.githubusercontent.com/5692308/41848791-fc32d006-787e-11e8-907f-43f7c06af161.png)

An imp_summoner hit the spearman, and knocked it back as expected. But only the image of the spearman was pushed back. His game position (the blue hexagon) didn't move. Afterwards, I could only select the spearman by clicking on his game position and not on the image of the spearman.

**Comment by StyMaar** [comment]
Version: v0.4.0 Linux pre-built binary.

**Comment by ozkriff** [comment]
Thanks for reporting! This one looks harder to debug, I'll try to reproduce and investigate what's going on.

**Comment by StyMaar** [comment]
Update: I've just reproduced this bug on master, with the hammerman.

![capture du 2018-06-27 11-37-09](https://user-images.githubusercontent.com/5692308/41966077-78cad304-79fe-11e8-98d8-cc5dcaacbc98.png)

**Comment by ozkriff** [comment]
Seems like this bug has something to do with low agent's health and/or death.

**Comment by StyMaar** [comment]
Death I don't think do, none of my two units triggering the death were about to die IIRC. And low life in itself isn't enough to reproduce.

**Comment by ozkriff** [comment]
Don't bother :)

I've created a tiny playground map (by editing `/src/core/execute.rs` and `objects.ron`) and quickly found out that to reproduce the bug you need:

- stay near an enemy who is ready for reaction attack and has `HeavyImpact` passive ability
- try to move away from him and trigger a reaction attack

Demo: https://imgur.com/sn7mSoJ

So the bug is somewhere inside the movement interruption code :bug:

**Comment by ozkriff** [comment]
95% sure that the bug is here - https://github.com/ozkriff/zemeroth/blob/feb3f6557/src/core/execute.rs#L55-L56

**Comment by ozkriff** [comment]
Should be fixed now! :)

**Comment by StyMaar** [comment]
Magnifique !
